### ISSUE TITLE
Must specify protocol for client-uvm sharing of signal handlers

### ISSUE THREAD

**Issue by mn200** [microvm/microvm-meta#1]
As per discussion in meeting on 1 August 2014, we think that the uVM should be the only entity making the `signal` system call.  Other entities (_i.e._, clients in practice) can register signal-handler-like objects with the uVM, which promises to pass on signals generated by their code.

This needs to be documented in the spec-wiki, perhaps in a section about client-uVM API.

**Comment by wks** [comment]
Added to a new section [µVM-Client Interface](https://github.com/microvm-project/microvm-spec/wiki/uvm-client-interface).
